In [ ]:
# Numpy was not a original package in python earlier
# Previously it was available in MATLAB
# NUMPY - NumericPython

In [1]:
import numpy as np 

In [2]:
#It is very powerful for numerical operations

In [3]:
#creation of array 

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
#type of this is "ndimesional array"

In [7]:
#Data can be inserted into any number of dimesion 

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.array([1,2,3,4,5,"vikas",4+8j])

array(['1', '2', '3', '4', '5', 'vikas', '(4+8j)'], dtype='<U11')

In [10]:
np.array([1,2,3,4,6.0,4.5])

array([1. , 2. , 3. , 4. , 6. , 4.5])

In [11]:
#We can able to see that it is "upcasting" the data 

#If the list of array has int and string , it is going to convert all the data into string 

#Hence it will convert data based higher order.

In [12]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [13]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [14]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-14-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [15]:
#it is able to create array but saying that it will give list objects in array 

In [17]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [21]:
#np.arry([])                ---- 1d array
#np.array([[1,3],[1,3]])    ---- 2d array
#np.array([[[1,2],[1,2]]])  ---- 3d array 

In [24]:
np.array([1,2,3], ndmin = 3)

#ndim gives us the dimesnion we want 

array([[[1, 2, 3]]])

In [26]:
np.array ([1,3,4] , dtype = complex)

#conversion of data into different data type...called type conversion

array([1.+0.j, 3.+0.j, 4.+0.j])

In [27]:
#Representation of data can be possible by visualsing them through axis

In [28]:
np.array([(1,2) , (4,5)])

array([[1, 2],
       [4, 5]])

In [29]:
#we can able to keep data in list or tuple but it will gives us list 

In [31]:
np.array([(1,2) , (4,5)] , dtype = [("a",'<i2'),('b','<i8')])

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [32]:
arr = np.array([(1,2) , (4,5)] , dtype = [("a",'<i2'),('b','<i8')])

In [33]:
arr[0]

(1, 2)

In [34]:
arr[0][0]

1

In [35]:
type(arr[0][0])

numpy.int16

In [36]:
type(arr[0][1])

numpy.int64

In [37]:
#Here ('a','b') are (1,2) & (4,5)

In [38]:
arr = np.array([[1,3],[3,4]])

In [39]:
arr

array([[1, 3],
       [3, 4]])

In [42]:
type(arr[0][1])

numpy.int32

In [43]:
#ANOTHER TYPE OF DATATYPE PRESENT IN NUMPY IS MATRIX

In [44]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [51]:
mat = np.mat(arr)

In [45]:
# we can use np.mat or np.matrix

In [46]:
l =[1,2,3,4,5,6]

In [48]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [49]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [55]:
np.asanyarray(mat)

#asanyarray checks that if dataset is present in form of array then it will not convert into array.
#matrix is also an array (subset/subclass of array )

matrix([[1, 3],
        [3, 4]])

In [54]:
np.asarray(mat)

#Here it will convert everything into array 

array([[1, 3],
       [3, 4]])

In [57]:
#checking whether matrix is subclass of array 
issubclass(np.matrix,np.ndarray)


True

# shallow and deep copy

In [58]:
arr

array([[1, 3],
       [3, 4]])

In [59]:
a = arr #represents shallow copy 

In [60]:
b = np.copy(arr)#represents deep copy 

In [61]:
arr[0][0] = 67

In [62]:
arr

array([[67,  3],
       [ 3,  4]])

In [63]:
a

#reflect new value that we assigned 

array([[67,  3],
       [ 3,  4]])

In [64]:
b
#getting old value of arr[0][0]

array([[1, 3],
       [3, 4]])

In [65]:
arr[-1]

array([3, 4])

In [66]:
arr[0:100]

array([[67,  3],
       [ 3,  4]])

In [67]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [68]:
#list is a part of core python
#Numpy helps in numerical approach 

In [69]:
np.fromfunction(lambda i,j : i == j ,[4,4])

#here [4,4] == rows * columns 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [71]:
np.fromfunction(lambda i,j : i*j , [3,3])

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [72]:
np.fromfunction(lambda i,j : i**j , [3,3])

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [73]:
np.fromfunction(lambda i,j : i/j , [3,3])

<ipython-input-73-01377cad87a2>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j : i/j , [3,3])
<ipython-input-73-01377cad87a2>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j : i/j , [3,3])


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [74]:
#In regular programming we get exceptions

# 'inf' is a keyword exist in numpy that doesn't gives error

In [76]:
gen =  (i*i for i in range(5))

In [77]:
def test(x):
    yield x

In [78]:
test(5)

<generator object test at 0x00000137806CDF20>

In [79]:
np.fromiter(gen , dtype = int)

array([ 0,  1,  4,  9, 16])

In [80]:
np.fromiter(range(5) , dtype = int)

array([0, 1, 2, 3, 4])

In [81]:
np.fromstring('1,2,3,4,5,6' , sep = ',')

array([1., 2., 3., 4., 5., 6.])

In [82]:
np.fromstring('1,2,3,4,5,6' , sep = ',', dtype = int)

array([1, 2, 3, 4, 5, 6])

In [84]:
np.fromstring('123 345 676 345 3445' , sep = " ", dtype = complex)

array([ 123.+0.j,  345.+0.j,  676.+0.j,  345.+0.j, 3445.+0.j])

In [85]:
l=[3,4,5,6,7]

In [87]:
arr = np.array(l)

In [92]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [93]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [94]:
type(arr)


numpy.ndarray

In [95]:
arr1.ndim

2

In [100]:
arr1.size

#tells total number of elements 

12

In [102]:
arr1.shape

#tells how many rows and columns 

(3, 4)

In [103]:
arr1.dtype

dtype('int32')

In [104]:
arr

array([3, 4, 5, 6, 7])

In [105]:
arr.size

5

In [106]:
arr.ndim

1

In [107]:
arr.shape

(5,)

In [108]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]]])

In [109]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [125]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [112]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [113]:
arr2.size

16

In [115]:
arr2.ndim

3

In [117]:
arr2.shape

#we have to read this as ... 2 number of 2*4 data 

#'n' number of i*j data (i,j == rows, columns)

(2, 2, 4)

In [118]:
#creation of 4d data 

In [123]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]],[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [124]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]],


       [[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [126]:
arr4.ndim

4

In [129]:
arr4.shape

#we have 2*4 matixes of 2 in 2

(2, 2, 2, 4)

In [131]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [133]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [134]:
np.arange(6.6)

#accepts float values 
#Able to access jumps with float 

array([0., 1., 2., 3., 4., 5., 6.])

In [136]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [137]:
np.arange(6.6,9,-.3)

array([], dtype=float64)

In [138]:
np.arange(9,6.6,-.6)

array([9. , 8.4, 7.8, 7.2, 6.6])

In [139]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [140]:
np.arange(1,9.1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [144]:
np.linspace(1,2)

#generate data in between line(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [143]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [146]:
np.linspace(1.1,1.3 ,num = 10)

#num : it gives us how many data we want 

# np.linspace(1,2,30)

array([1.1       , 1.12222222, 1.14444444, 1.16666667, 1.18888889,
       1.21111111, 1.23333333, 1.25555556, 1.27777778, 1.3       ])

In [148]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [149]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [150]:
np.ones(4)

array([1., 1., 1., 1.])

In [151]:
np.ones(3 , dtype = int)

array([1, 1, 1])

In [152]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [156]:
np.ones((2,3,2)) + 5

#add '5' to every element 

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [158]:
np.empty(3)

array([0., 1., 2.])

In [160]:
np.eye(3)

#eye  represents identity matrix 

#identity matrix : all diagonal elements = 1, matrix = 1np.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [162]:
np.linspace(2,4,4,endpoint=False)

#endppoint = false : not include upper bound 

array([2. , 2.5, 3. , 3.5])

In [163]:
np.linspace([2,4],4,endpoint=False,axis = 0)

#axis = 0 : generate data in row fashion 

array([[2.  , 4.  ],
       [2.04, 4.  ],
       [2.08, 4.  ],
       [2.12, 4.  ],
       [2.16, 4.  ],
       [2.2 , 4.  ],
       [2.24, 4.  ],
       [2.28, 4.  ],
       [2.32, 4.  ],
       [2.36, 4.  ],
       [2.4 , 4.  ],
       [2.44, 4.  ],
       [2.48, 4.  ],
       [2.52, 4.  ],
       [2.56, 4.  ],
       [2.6 , 4.  ],
       [2.64, 4.  ],
       [2.68, 4.  ],
       [2.72, 4.  ],
       [2.76, 4.  ],
       [2.8 , 4.  ],
       [2.84, 4.  ],
       [2.88, 4.  ],
       [2.92, 4.  ],
       [2.96, 4.  ],
       [3.  , 4.  ],
       [3.04, 4.  ],
       [3.08, 4.  ],
       [3.12, 4.  ],
       [3.16, 4.  ],
       [3.2 , 4.  ],
       [3.24, 4.  ],
       [3.28, 4.  ],
       [3.32, 4.  ],
       [3.36, 4.  ],
       [3.4 , 4.  ],
       [3.44, 4.  ],
       [3.48, 4.  ],
       [3.52, 4.  ],
       [3.56, 4.  ],
       [3.6 , 4.  ],
       [3.64, 4.  ],
       [3.68, 4.  ],
       [3.72, 4.  ],
       [3.76, 4.  ],
       [3.8 , 4.  ],
       [3.84, 4.  ],
       [3.88,

In [164]:
np.linspace([2,4],4,endpoint=False,axis = 1)
#axis = 1 : generates data in column fashion

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [166]:
np.logspace(2,3,5)

#shows logrithmic data 

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [167]:
np.logspace([2,3],5)

array([[   100.        ,   1000.        ],
       [   115.13953993,   1098.54114199],
       [   132.57113656,   1206.79264064],
       [   152.64179672,   1325.71136559],
       [   175.75106249,   1456.3484775 ],
       [   202.35896477,   1599.85871961],
       [   232.99518105,   1757.51062485],
       [   268.26957953,   1930.69772888],
       [   308.88435965,   2120.95088792],
       [   355.64803062,   2329.95181052],
       [   409.49150624,   2559.5479227 ],
       [   471.48663635,   2811.76869797],
       [   542.86754393,   3088.84359648],
       [   625.05519253,   3393.2217719 ],
       [   719.685673  ,   3727.59372031],
       [   828.64277285,   4094.91506238],
       [   954.09547635,   4498.43266897],
       [  1098.54114199,   4941.71336132],
       [  1264.85521686,   5428.67543932],
       [  1456.3484775 ,   5963.62331659],
       [  1676.83293681,   6551.2855686 ],
       [  1930.69772888,   7196.85673001],
       [  2222.99648253,   7906.04321091],
       [  2

In [168]:
np.logspace([2,3],5, axis = 1)

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [169]:
np.logspace([2],[3],axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [170]:
d = np.linspace(4,7,40)

In [171]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [172]:
d.ndim

1

In [173]:
d.shape

(40,)

In [174]:
#change dimesnions of 'd'

In [177]:
d.reshape(40,1)

#40 rows , 1 column 

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [178]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [179]:
#conversion of data into diff dimensions using .reshape

# RANDOM DATA GENERATION.

In [180]:
np.random.rand(3)

array([0.24222888, 0.26114189, 0.74259871])

In [181]:
#what ever the data is been generated is from the gaussian distribution

In [182]:
np.random.randn(4)

array([-0.15879621, -0.53195379, -0.66922345,  0.28782778])

In [183]:
#rand = data based on normal (or) uniform distribution 
#randn = data based on standard distribution (mean always = 0)

In [184]:
np.random.randn(2,3)

array([[ 0.87995395, -0.01155369, -1.24505006],
       [ 0.03863232,  0.99501777, -0.45354161]])

In [185]:
np.random.randn(2,2,3)

array([[[-1.46425852,  0.44411891, -0.91663706],
        [ 0.82982612,  0.24286415, -0.43954983]],

       [[ 1.42612474,  0.86026673, -1.25848564],
        [-0.18498254, -0.1417281 ,  1.43987021]]])

In [187]:
np.random.randint(5,6)

5

In [188]:
#rand
#randn
#randint

In [190]:
np.random.randint(5,60,(4,4))

#generates 4*4 data, available between 5 & 60

array([[11, 37, 47, 22],
       [21,  5, 48,  6],
       [53, 36, 45, 25],
       [32, 16, 34, 14]])

In [191]:
arr = np.random.randint(3,9,(3,3))

In [192]:
arr

array([[6, 8, 3],
       [6, 7, 5],
       [4, 7, 5]])

In [196]:
arr.reshape(1,9)

#1 row * 9 columns = 9 total_elements

#always reshape should be done based on the size of dataset

array([[6, 8, 3, 6, 7, 5, 4, 7, 5]])

In [198]:
arr.reshape(9,1)

#9 rows * 1 column = 9 total_elements

array([[6],
       [8],
       [3],
       [6],
       [7],
       [5],
       [4],
       [7],
       [5]])

In [199]:
arr.reshape(1,1,9)

array([[[6, 8, 3, 6, 7, 5, 4, 7, 5]]])

In [200]:
arr.reshape(3,3,1)

array([[[6],
        [8],
        [3]],

       [[6],
        [7],
        [5]],

       [[4],
        [7],
        [5]]])

In [202]:
arr.reshape(3,-1)

#"it will be able to generate array if first number is mentioned "

array([[6, 8, 3],
       [6, 7, 5],
       [4, 7, 5]])

In [204]:
arr.reshape(3,-456789)

#It is possible to reshape the array as first number is specified

array([[6, 8, 3],
       [6, 7, 5],
       [4, 7, 5]])

In [205]:
arr.reshape(1,-234567890)

array([[6, 8, 3, 6, 7, 5, 4, 7, 5]])

In [206]:
arr

array([[6, 8, 3],
       [6, 7, 5],
       [4, 7, 5]])

In [208]:
arr.max()

#gives maximum element of the array

8

In [210]:
arr.min()

#gives minimun data in the array 

3

In [213]:
arr = np.random.randint(4,100,(5,5))

In [214]:
arr

array([[41, 44, 46, 65, 50],
       [44, 94, 69, 40, 29],
       [78, 81, 54, 98, 50],
       [43,  8, 34, 23, 41],
       [56, 39, 73, 63, 51]])

In [215]:
#Getting out of particular data 

In [221]:
arr[3: ,3: ]

array([[23, 41],
       [63, 51]])

In [222]:
arr[0:,[1,3]]

array([[44, 65],
       [94, 40],
       [81, 98],
       [ 8, 23],
       [39, 63]])

In [223]:
 arr

array([[41, 44, 46, 65, 50],
       [44, 94, 69, 40, 29],
       [78, 81, 54, 98, 50],
       [43,  8, 34, 23, 41],
       [56, 39, 73, 63, 51]])

In [224]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [226]:
arr[arr>10]

#filter out data which is greater than 10 

array([41, 44, 46, 65, 50, 44, 94, 69, 40, 29, 78, 81, 54, 98, 50, 43, 34,
       23, 41, 56, 39, 73, 63, 51])

In [228]:
arr 

array([[41, 44, 46, 65, 50],
       [44, 94, 69, 40, 29],
       [78, 81, 54, 98, 50],
       [43,  8, 34, 23, 41],
       [56, 39, 73, 63, 51]])

In [229]:
#multiplication 
arr * arr

array([[1681, 1936, 2116, 4225, 2500],
       [1936, 8836, 4761, 1600,  841],
       [6084, 6561, 2916, 9604, 2500],
       [1849,   64, 1156,  529, 1681],
       [3136, 1521, 5329, 3969, 2601]])

In [232]:
arr1 = np.random.randint(2,4,(3,3))

In [233]:
arr1


array([[3, 3, 2],
       [3, 3, 2],
       [3, 2, 3]])

In [234]:
arr2 = np.random.randint(2,4,(3,3))

In [235]:
arr2

array([[2, 2, 3],
       [3, 2, 3],
       [3, 3, 3]])

In [236]:
arr1 * arr2

array([[6, 6, 6],
       [9, 6, 6],
       [9, 6, 9]])

In [237]:
#this is not a matrix multiplication 

In [238]:
arr1 @ arr2 

array([[21, 18, 24],
       [21, 18, 24],
       [21, 19, 24]])

In [239]:
#arr1 @ arr2 "@" this tells that it is a matrix multiplication 

In [240]:
arr/0

<ipython-input-240-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [241]:
arr ** 2

#finds out square 

array([[1681, 1936, 2116, 4225, 2500],
       [1936, 8836, 4761, 1600,  841],
       [6084, 6561, 2916, 9604, 2500],
       [1849,   64, 1156,  529, 1681],
       [3136, 1521, 5329, 3969, 2601]], dtype=int32)

# BROADCASTING 

In [242]:
arr = np.zeros((3,4))

In [243]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [244]:
 a = np.array([1,2,3,4])

In [245]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [246]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [247]:
b= np.array([5,6,7])

In [248]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [249]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [250]:
#in the above case we are adding column wise

In [251]:
b

array([5, 6, 7])

In [253]:
b= np.array([[5,6,7]])

In [254]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [255]:
#broadcasting of single data with every rows n columns

In [256]:
arr = np.random.randn(5,4)

In [257]:
arr

array([[-0.21266296,  1.79195392, -0.59171066, -0.02544874],
       [ 0.73090966,  0.66386742,  1.00992317,  1.93999409],
       [ 0.26162848, -0.43231507, -0.45447976,  0.24491592],
       [ 0.02025792,  0.71096396, -1.40302755,  0.52643345],
       [ 0.76135514,  0.49662678,  1.09145012, -0.44870864]])

In [258]:
#sqrt of all data

In [259]:
np.sqrt(arr)

<ipython-input-259-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[       nan, 1.33863883,        nan,        nan],
       [0.85493255, 0.81478059, 1.00494934, 1.39283671],
       [0.51149632,        nan,        nan, 0.4948898 ],
       [0.14233033, 0.84318679,        nan, 0.72555734],
       [0.87255667, 0.70471752, 1.0447249 ,        nan]])

In [260]:
np.exp(arr)

array([[0.80842856, 6.00116682, 0.55337983, 0.97487235],
       [2.07696909, 1.94228947, 2.74539008, 6.95870984],
       [1.29904383, 0.64900486, 0.63477812, 1.27751389],
       [1.02046451, 2.03595289, 0.24585151, 1.69288377],
       [2.14117584, 1.64316913, 2.97859026, 0.63845209]])

In [261]:
np.log10(arr)

<ipython-input-261-4473232fb1a0>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([[        nan,  0.25332684,         nan,         nan],
       [-0.1361363 , -0.17791865,  0.00428834,  0.28780041],
       [-0.58231498,         nan,         nan, -0.61098299],
       [-1.69340506, -0.14815241,         nan, -0.27865653],
       [-0.11841272, -0.30396987,  0.03800389,         nan]])

In [262]:
arr1 = np.random.randint(2,5,(5,5))

In [264]:
arr1

array([[2, 3, 4, 4, 4],
       [4, 4, 4, 4, 2],
       [4, 4, 2, 4, 3],
       [4, 3, 4, 3, 3],
       [4, 3, 4, 3, 4]])

In [265]:
np.log10(arr1)
#finding logrithmic of arr1

array([[0.30103   , 0.47712125, 0.60205999, 0.60205999, 0.60205999],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.30103   ],
       [0.60205999, 0.60205999, 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.47712125, 0.60205999]])